name: Test Server version

on:
  push:
    branches: [shruti/PSD-1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses : jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env :
        JF_URL : https://genesisglobal.jfrog.io/genesisglobal
        JF_USER : ${{ secrets.JFROG_LIBS_RELEASE_CLIENT_RO_USER }}
        JF_PASSWORD : ${{ secrets.JFROG_LIBS_RELEASE_CLIENT_RO_PASSWORD }}
    - run : |
        jf rt ping
        jf rt s "libs-release-client/global/genesis/genesis-distribution/" --sort-by=created --sort-order=desc --limit=1
